#!/usr/bin/env python3
"""
prove_roundtrip.py — Ultimate proof of TTS+STT quality.

Takes WAV files generated by TTS, feeds them through STT, and compares
the output transcript to the original input text. Low WER proves both
systems are human-level intelligible working together.

Usage:
    python scripts/prove_roundtrip.py \
        --stt-model models/parakeet-tdt-0.6b-v2.cstt \
        --wav-dir bench_output/tts_c \
        --output bench_output/roundtrip_proof.json
"""

import argparse
import ctypes
import json
import re
import sys
import time
from pathlib import Path

import numpy as np
import soundfile as sf

TEST_SENTENCES = [
    "Hello, how are you today?",
    "The quick brown fox jumps over the lazy dog.",
    "Artificial intelligence is transforming the world.",
    "Can you please tell me where the nearest hospital is?",
    "It was the best of times, it was the worst of times.",
    "Technology continues to advance at an unprecedented pace.",
    "The weather forecast predicts rain for the entire weekend.",
    "She sold seashells by the seashore.",
    "To be or not to be, that is the question.",
    "A stitch in time saves nine.",
    "The restaurant on Rue de Rivoli serves excellent coq au vin.",
    "Please welcome Doctor Miller from Zurich and CEO Satoshi Nakamura.",
    "I'm so excited to tell you this, you won the grand prize!",
    "I'm deeply sorry for your loss. Please know that I'm here for you.",
    "Let me think about that for a moment. Actually, yes, I believe so.",
    "We hold these truths to be self-evident, that all men are created equal.",
    "The only thing we have to fear is fear itself.",
    "In the beginning was the Word, and the Word was with God.",
    "It is a truth universally acknowledged that a single man in possession of a good fortune must be in want of a wife.",
    "To infinity and beyond!",
    "Houston, we have a problem.",
    "That's one small step for man, one giant leap for mankind.",
    "The temperature outside is negative fifteen degrees Celsius.",
    "Please call nine one one immediately, there's been an accident.",
    "The stock market rose by three point seven percent yesterday.",
]


def normalize_text(text):
    """Normalize text for fair WER comparison."""
    text = text.lower()
    text = re.sub(r"[^\w\s']", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def word_error_rate(ref, hyp):
    """Levenshtein WER."""
    r = ref.split()
    h = hyp.split()
    d = [[0] * (len(h) + 1) for _ in range(len(r) + 1)]
    for i in range(len(r) + 1):
        d[i][0] = i
    for j in range(len(h) + 1):
        d[0][j] = j
    for i in range(1, len(r) + 1):
        for j in range(1, len(h) + 1):
            if r[i - 1] == h[j - 1]:
                d[i][j] = d[i - 1][j - 1]
            else:
                d[i][j] = 1 + min(d[i - 1][j], d[i][j - 1], d[i - 1][j - 1])
    return d[len(r)][len(h)] / max(len(r), 1)


def resample_24k_to_16k(audio, orig_sr=24000, target_sr=16000):
    """Simple resampling from 24kHz to 16kHz using linear interpolation."""
    ratio = target_sr / orig_sr
    n_out = int(len(audio) * ratio)
    indices = np.arange(n_out) / ratio
    idx_floor = np.floor(indices).astype(int)
    idx_ceil = np.minimum(idx_floor + 1, len(audio) - 1)
    frac = indices - idx_floor
    return audio[idx_floor] * (1 - frac) + audio[idx_ceil] * frac


def main():
    parser = argparse.ArgumentParser(description="Round-trip TTS→STT proof")
    parser.add_argument("--stt-model", required=True, help="Path to .cstt model")
    parser.add_argument("--wav-dir", default="bench_output/tts_c",
                        help="Directory with TTS WAV samples")
    parser.add_argument("--output", default="bench_output/roundtrip_proof.json",
                        help="Output JSON")
    parser.add_argument("--streaming", action="store_true",
                        help="Use streaming STT mode")
    args = parser.parse_args()

    lib_path = Path("build/libconformer_stt.dylib")
    if not lib_path.exists():
        print(f"ERROR: {lib_path} not found.", file=sys.stderr)
        sys.exit(1)

    lib = ctypes.CDLL(str(lib_path))
    lib.conformer_stt_create.argtypes = [ctypes.c_char_p]
    lib.conformer_stt_create.restype = ctypes.c_void_p
    lib.conformer_stt_process.argtypes = [ctypes.c_void_p, ctypes.POINTER(ctypes.c_float), ctypes.c_int]
    lib.conformer_stt_process.restype = ctypes.c_int
    lib.conformer_stt_flush.argtypes = [ctypes.c_void_p]
    lib.conformer_stt_flush.restype = ctypes.c_int
    lib.conformer_stt_get_text.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_int]
    lib.conformer_stt_get_text.restype = ctypes.c_int
    lib.conformer_stt_reset.argtypes = [ctypes.c_void_p]
    lib.conformer_stt_destroy.argtypes = [ctypes.c_void_p]
    lib.conformer_stt_set_cache_aware.argtypes = [ctypes.c_void_p, ctypes.c_int]

    engine = lib.conformer_stt_create(args.stt_model.encode())
    if not engine:
        print(f"ERROR: Failed to load model {args.stt_model}", file=sys.stderr)
        sys.exit(1)

    if args.streaming:
        lib.conformer_stt_set_cache_aware(engine, 1)

    wav_dir = Path(args.wav_dir)
    results = []
    total_wer = 0.0
    total_words = 0
    total_errors = 0
    perfect = 0

    print("\n" + "=" * 70)
    print("ROUND-TRIP PROOF: TTS WAV \u2192 STT \u2192 Compare")
    print("=" * 70)
    mode = "streaming" if args.streaming else "non-streaming"
    print(f"  STT model: {args.stt_model}")
    print(f"  Mode: {mode}")
    print(f"  WAV dir: {args.wav_dir}")
    print()

    for idx, original_text in enumerate(TEST_SENTENCES):
        wav_path = wav_dir / f"sample_{idx:02d}.wav"
        if not wav_path.exists():
            print(f"  [{idx:2d}] SKIP — {wav_path} not found")
            continue

        audio, sr = sf.read(str(wav_path), dtype="float32")
        if sr != 16000:
            audio = resample_24k_to_16k(audio, sr, 16000)

        lib.conformer_stt_reset(engine)
        if args.streaming:
            lib.conformer_stt_set_cache_aware(engine, 1)

        audio_f32 = audio.astype(np.float32)
        audio_ptr = audio_f32.ctypes.data_as(ctypes.POINTER(ctypes.c_float))

        t0 = time.perf_counter()
        lib.conformer_stt_process(engine, audio_ptr, len(audio_f32))
        lib.conformer_stt_flush(engine)
        elapsed = time.perf_counter() - t0

        buf = ctypes.create_string_buffer(8192)
        lib.conformer_stt_get_text(engine, buf, 8192)
        transcript = buf.value.decode("utf-8", errors="replace").strip()

        ref_norm = normalize_text(original_text)
        hyp_norm = normalize_text(transcript)
        wer = word_error_rate(ref_norm, hyp_norm)

        ref_words = ref_norm.split()
        n_words = len(ref_words)
        n_errors = round(wer * n_words)
        total_words += n_words
        total_errors += n_errors
        is_perfect = (wer == 0.0)
        if is_perfect:
            perfect += 1

        status = "\u2713 PERFECT" if is_perfect else f"WER={wer*100:.1f}%"
        audio_dur = len(audio) / 16000
        rtf = elapsed / audio_dur if audio_dur > 0 else 0

        print(f"  [{idx:2d}] {status:>12s}  RTF={rtf:.3f}  ({elapsed*1000:.0f}ms / {audio_dur:.1f}s)")
        if not is_perfect:
            print(f"         REF: {ref_norm[:80]}")
            print(f"         HYP: {hyp_norm[:80]}")

        results.append({
            "idx": idx,
            "original": original_text,
            "ref_norm": ref_norm,
            "transcript": transcript,
            "hyp_norm": hyp_norm,
            "wer": wer,
            "audio_duration_s": audio_dur,
            "processing_s": elapsed,
            "rtf": rtf,
            "perfect": is_perfect,
        })

    overall_wer = total_errors / max(total_words, 1)
    n_tested = len(results)

    print()
    print("=" * 70)
    print("ROUND-TRIP RESULTS")
    print("=" * 70)
    print(f"  Sentences tested:  {n_tested}")
    print(f"  Perfect matches:   {perfect}/{n_tested} ({100*perfect/max(n_tested,1):.0f}%)")
    print(f"  Overall WER:       {overall_wer*100:.2f}%")
    print(f"  Total words:       {total_words}")
    print(f"  Total errors:      {total_errors}")
    avg_rtf = np.mean([r["rtf"] for r in results]) if results else 0
    print(f"  Avg RTF:           {avg_rtf:.4f}x")
    print()

    if overall_wer < 0.05:
        grade = "A — HUMAN-LEVEL"
    elif overall_wer < 0.10:
        grade = "B — EXCELLENT"
    elif overall_wer < 0.20:
        grade = "C — GOOD"
    else:
        grade = "D — NEEDS WORK"
    print(f"  GRADE: {grade}")
    print("=" * 70)

    output = {
        "stt_model": args.stt_model,
        "mode": mode,
        "n_sentences": n_tested,
        "perfect_matches": perfect,
        "overall_wer": overall_wer,
        "total_words": total_words,
        "total_errors": total_errors,
        "avg_rtf": avg_rtf,
        "grade": grade,
        "per_sentence": results,
    }

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\n  Results saved to {args.output}")


if __name__ == "__main__":
    main()
